# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App_Ticket' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod'SideMenu'
  # Pods for App_Ticket

  target 'App_TicketTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'App_TicketUITests' do
    # Pods for testing
  end

end
